{
 "title": "Prefect",
 "description": "Prefect flows stats",
 "tags": [ "prefect" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "project",
    "query": {
     "query": "label_values(prefect_projects, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flow Run Percent Success by Project",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (prefect_flowruns_success{project_name!=\"\"} / (prefect_flowruns_success{project_name!=\"\"} + prefect_flowruns_failed{project_name!=\"\"})) * 100 > 0",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Upcoming Flows",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flowruns_upcoming{project_name=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Active Flows Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flowruns_running) by (project_name)"
    }
   ]
  },
  {
   "title": "Success Flows Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_flowruns_success{project_name=~\"$project\"}) / sum(prefect_flowruns_total{project_name=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Failed Flow Rate - 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prefect_flowruns_failed[1d])",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  { "title": "Running", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Flows per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(prefect_flowruns_success{project_name!=\"\"}[1h]))",
     "legendFormat": "Flows success {{ project_name }}"
    },
    {
     "expr": "sum(increase(prefect_flows_total_failed{project_name!=\"\"}[1h]))",
     "legendFormat": "Flows failed {{ project_name }}"
    }
   ]
  },
  {
   "title": "Flows Run Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prefect_flowruns_success{project_name!=\"\"} / (prefect_flowruns_failed{project_name!=\"\"} + prefect_flowruns_success{project_name!=\"\"}) * 100",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Flow Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Flow Count" }
   ],
   "targets": [
    {
     "expr": "sum(prefect_flows_by_project) by (project_name)",
     "legendFormat": "{{ project_name }}"
    }
   ]
  }
 ]
}